# Generated by Django 4.0.3 on 2022-03-23 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 3, 23, 9, 13, 13, 446997, tzinfo=utc))),
            ],
        ),
    ]
